import type {Metadata} from 'next'
import UserNavbar from "@/components/userNavbar";

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function KtererLayout({children}: {
    children: React.ReactNode
}) {
    return (
        <section>
            <UserNavbar/>
            {children}
        </section>
    )
}



